Async Storage Transactions
ailohq/knex-utils pull request #24
Opened 2022-04-14 05:10 UTC by Smtih

This PR adds the `transact` and `transactional` methods that live in many of our services that use `knex` and looks to implement them more similarly to Java frameworks that use thread storage.

Originally inspired by https://github.com/odavid/typeorm-transactional-cls-hooked
This uses the AsyncLocalStorage API which is mostly stable as of nodejs 16 (though the parts we're using haven't changed since nodejs 14)
https://nodejs.org/docs/latest-v16.x/api/async_context.html#class-asynclocalstorage

This is coupled with an objection mixin which allows transactions to propogate all the way to the database layer without having to manually pass trx objects around our code.

2022-04-22 02:48 UTC, Alex-McLean requested changes
Looks pretty good to me, just some thoughts on typing and possible additional tests.

2022-04-22 02:48 UTC, Alex-McLean commented on src/transactions/TransactionManager.ts
> +export function transactional(transactionManager: TransactionManager) {
Maybe add `MethodDecorator` as the return type, was not immediately clear whilst reading this file in isolation that this is a decorator.

2022-04-22 02:48 UTC, Alex-McLean commented on src/transactions/TransactionMixin.ts
> +      static query<M extends Model>(
Unsure what the correct solution here is, but these generics (`M extends Model`) have no relation to `BaseModel` nor the `MC` generic, and as such do not provide any strong typing at runtime against anything other than `Model`.
This can be verified by observing the IDE type inferences of `TestModel.query` in the test file, unsure if this is a major issue, however I believe it may be ideal at runtime if `TestModel.query` retained the full typing of `TestModel` rather than just `Model`.

Also applies to `.relatedQuery`.

2022-04-22 02:48 UTC, Alex-McLean commented on src/transactions/tests/TransactionMixin.test.ts
> +  it("should get transaction from transaciton manager when calling static query", async () => {
Typo in transaction in all test descriptions

2022-04-22 02:48 UTC, Alex-McLean commented on src/transactions/tests/TransactionManager.test.ts
> +  it("should get transaction if in transact", async () => {
Worth adding a test for nested `transact` calls?

```typescript
it("should get transaction if in nested transact", async () => {
  const transaction = await transactionManager.transact(() => {
    return transactionManager.transact(() => {
      return Promise.resolve(transactionManager.getTransaction());
    });
  });
  expect(transaction).toBe(mockTransaction);
});
```

2022-04-22 02:48 UTC, Alex-McLean commented on src/transactions/tests/TransactionMixin.test.ts
> +    expect(mockTransactionManager.tryGetTransaction).toHaveBeenCalledTimes(1);
Worth also verifying that the `mockQueryBuilder` is returned?

Applies to all tests in this file.

2022-04-22 02:48 UTC, Alex-McLean commented on src/transactions/tests/TransactionMixin.test.ts
> +  it("should get transaction from transaciton manager when calling static query", async () => {
Also worth testing that the transaction manager is not used when a `trxOrKnex` is provided?

Applies to all tests in this file.

2022-04-25 22:55 UTC, Smtih commented on src/transactions/TransactionMixin.ts
> +      static query<M extends Model>(
I thought as a typed the return type of this function to be `MC` explicitly, the weaker typing in this class should be overwritten.
I had a lot of trouble getting something typescript would be happy with following this mixing pattern 🤦

2022-04-26 00:52 UTC, Smtih commented on src/transactions/TransactionManager.ts
> +    const transaction = this.transactionStorage.getStore();
Resolved here: https://github.com/ailohq/knex-utils/pull/24/commits/5a3e4dd554d1227694d8ece51c6170556c6cfffb

2022-04-26 00:52 UTC, Smtih commented on src/transactions/TransactionManager.ts
> +export function transactional(transactionManager: TransactionManager) {
resolved here: https://github.com/ailohq/knex-utils/pull/24/commits/de0e933eed33dc567bc76c1761b29fa4911f3313

2022-04-26 00:53 UTC, Smtih commented on src/transactions/TransactionMixin.ts
> +      static query<M extends Model>(
resolved here: https://github.com/ailohq/knex-utils/pull/24/commits/b1e5664173d4a15b2a0c872bd0c2bfaf6523b045

2022-04-26 00:53 UTC, Smtih commented on src/transactions/tests/TransactionMixin.test.ts
> +  it("should get transaction from transaciton manager when calling static query", async () => {
resolved here: https://github.com/ailohq/knex-utils/pull/24/commits/20e67c169425d416765d0f9ef23d9dcb70902a57

2022-04-26 00:53 UTC, Smtih commented on src/transactions/tests/TransactionMixin.test.ts
> +    expect(mockTransactionManager.tryGetTransaction).toHaveBeenCalledTimes(1);
resolved here: https://github.com/ailohq/knex-utils/pull/24/commits/8b41d79e855dbbf00cb9733510061518644c5ef1

2022-04-26 00:53 UTC, Smtih commented on src/transactions/tests/TransactionMixin.test.ts
> +  it("should get transaction from transaciton manager when calling static query", async () => {
resolved here: https://github.com/ailohq/knex-utils/pull/24/commits/764914221d99e7261d38cb07cc79334f46d0eb03

2022-04-26 00:54 UTC, Smtih commented on src/transactions/tests/TransactionManager.test.ts
> +  it("should get transaction if in transact", async () => {
resolved here: https://github.com/ailohq/knex-utils/pull/24/commits/5eb9bbdfe8171fda1eefa174d556f503c3608c61

2022-04-26 04:26 UTC, Alex-McLean approved these changes
:tada: LGTM

2022-04-26 04:32 UTC, merged